export default {
  IPSS: {
    "1AS - 1BS": [
      "Lingua e letteratura italiana",
      "Storia, cittadinanza e Costituzione",
      "Geografia",
      "Inglese",
      "Francese",
      "Matematica",
      "Metodologie operative",
      "Scienze umane e sociali",
      "Diritto, economia",
      "Tecnologie informatiche (TIC)",
      "Scienze sportive e motorie",
      "Religione Cattolica",
    ],
    "2AS - 2BS": [
      "Lingua e letteratura italiana",
      "Storia, cittadinanza e Costituzione",
      "Inglese",
      "Francese",
      "Matematica",
      "Metodologie operative",
      "Scienze umane e sociali",
      "Diritto, economia",
      "Tecnologie informatiche(TIC)",
      "Scienze sportive e motorie",
      "Religione Cattolica",
    ],
    "3AS - 3BS": [
      "Lingua e letteratura italiana",
      "Storia, cittadinanza e Costituzione",
      "Inglese",
      "Francese",
      "Matematica",
      "Metodologie operative",
      "Diritto, economia e legislazione sociosanitaria",
      "Psicologia generale ed applicata",
      "Igiene e cultura medico sanitaria",
      "Scienze sportive e motorie",
      "Religione Cattolica",
    ],
    "4AS - 4BS": [
      "Lingua e letteratura italiana",
      "Storia, cittadinanza e Costituzione",
      "Inglese",
      "Francese",
      "Matematica",
      "Metodologie operative",
      "Diritto, economia e legislazione sociosanitaria",
      "Psicologia generale ed applicata",
      "Igiene e cultura medico sanitaria",
      "Scienze sportive e motorie",
      "Religione Cattolica",
    ],
    "5AS - 5BS - 5CS": [
      "Lingua e letteratura italiana",
      "Storia, cittadinanza e Costituzione",
      "Inglese",
      "Francese",
      "Matematica",
      "Metodologie operative",
      "Diritto, economia e legislazione sociosanitaria",
      "Psicologia generale ed applicata",
      "Igiene e cultura medico sanitaria",
      "Scienze sportive e motorie",
      "Religione Cattolica",
    ],
  },
  ITC: {
    "1AE - 1BE": [
      "Lingua e letteratura italiana",
      "Storia",
      "Inglese",
      "Francese",
      "Geografia",
      "Matematica",
      "Scienze della Terra",
      "Fisica",
      "Informatica",
      "Economia Aziendale",
      "Diritto ed Economia",
      "Scienze Motorie e sportive",
      "Religione Cattolica",
    ],
    "2AE - 2BE": [
      "Lingua e letteratura italiana",
      "Storia",
      "Inglese",
      "Francese",
      "Geografia",
      "Matematica",
      "Biologia",
      "Chimica",
      "Informatica",
      "Economia Aziendale",
      "Diritto ed Economia",
      "Scienze Motorie e sportive",
      "Religione Cattolica",
    ],
    "3EE": [
      "Lingua e letteratura italiana",
      "Religione Cattolica",
      "Storia, Cittadinanza e Costituzione",
      "Matematica",
      "Inglese",
      "Francese",
      "Tedesco",
      "Tecnologie della Comunicazione",
      "Economia Aziendale e geo-politica",
      "Diritto",
      "Relazioni internazionali",
      "Scienze Motorie e sportive",
      "Religione Cattolica",
    ],
    "3PE": [
      "Lingua e letteratura italiana",
      "Storia, Cittadinanza e Costituzione",
      "Inglese",
      "Francese",
      "Informatica",
      "Matematica",
      "Economia Aziendale",
      "Diritto",
      "Economia Politica (CLIL)",
      "Scienze Motorie",
      "Religione Cattolica",
    ],
    "4EE": [
      "Lingua e letteratura italiana",
      "Religione Cattolica",
      "Storia, Cittadinanza e Costituzione",
      "Matematica",
      "Inglese",
      "Francese",
      "Tedesco",
      "Tecnologie della Comunicazione",
      "Economia Aziendale e geo-politica",
      "Diritto",
      "Relazioni internazionali",
      "Scienze Motorie e sportive",
      "Religione Cattolica",
    ],
    "4PE": [
      "Lingua e letteratura italiana",
      "Storia, Cittadinanza e Costituzione",
      "Inglese",
      "Informatica",
      "Matematica",
      "Economia Aziendale",
      "Diritto",
      "Economia Politica (CLIL)",
      "Scienze Motorie",
      "Religione Cattolica",
    ],
    "5EE": [
      "Lingua e letteratura italiana",
      "Religione Cattolica",
      "Storia, Cittadinanza e Costituzione",
      "Matematica",
      "Inglese",
      "Francese",
      "Tedesco",
      "Economia Aziendale e geo-politica",
      "Diritto",
      "Relazioni internazionali",
      "Scienze Motorie e sportive",
      "Religione Cattolica",
    ],
    "5PE": [
      "Lingua e letteratura italiana",
      "Storia, Cittadinanza e Costituzione",
      "Inglese",
      "Informatica",
      "Matematica",
      "Economia Aziendale",
      "Diritto",
      "Economia Politica (CLIL)",
      "Scienze Motorie",
      "Religione Cattolica",
    ],
  },
  ITIS: {
    "1AT - 1BT": [
      "Lingua e letteratura italiana",
      "Storia, cittadinanza e Costituzione",
      "Geografia",
      "Matematica",
      "Inglese",
      "Diritto ed economia",
      "Scienze della Terra",
      "Fisica",
      "Chimica",
      "Tecnologie e tecniche di rappresentazione grafica",
      "Tecnologie informatiche",
      "Scienze sportive e motorie",
      "Religione Cattolica",
    ],
    "2AT - 2BT": [
      "Lingua e letteratura italiana",
      "Storia, cittadinanza e Costituzione",
      "Matematica",
      "Inglese",
      "Diritto ed economia",
      "Biologia",
      "Fisica",
      "Chimica",
      "Tecnologie e tecniche di rappresentazione grafica",
      "Scienze sportive e motorie",
      "Religione Cattolica",
      "Scienze e tecnologie applicate",
    ],
    "3AT - 3BT": [
      "Lingua e letteratura italiana",
      "Storia, cittadinanza e Costituzione",
      "Matematica",
      "Inglese",
      "Scienze sportive e motorie",
      "Religione Cattolica",
      "Meccanica, macchine ed energia",
      "Sistemi ed Automazione",
      "Tecnologie meccaniche di Processo e di Prodotto",
      "Disegno, progettazione e Organizzazione Industriale",
    ],
    "4AT - 4BT": [
      "Lingua e letteratura italiana",
      "Storia, cittadinanza e Costituzione",
      "Matematica",
      "Inglese",
      "Scienze sportive e motorie",
      "Religione Cattolica",
      "Meccanica, macchine ed energia",
      "Sistemi ed Automazione",
      "Tecnologie meccaniche di Processo e di Prodotto",
      "Disegno, progettazione e Organizzazione Industriale",
    ],
    "5AT - 5BT": [
      "Lingua e letteratura italiana",
      "Storia, cittadinanza e Costituzione",
      "Matematica",
      "Inglese",
      "Scienze sportive e motorie",
      "Religione Cattolica",
      "Meccanica, macchine ed energia",
      "Sistemi ed Automazione",
      "Tecnologie meccaniche di Processo e di Prodotto",
      "Disegno, progettazione e Organizzazione Industriale",
    ],
    "1CT": [
      "Lingua e letteratura italiana",
      "Storia, cittadinanza e Costituzione",
      "Geografia",
      "Matematica",
      "Inglese",
      "Diritto ed economia",
      "Scienze della Terra",
      "Fisica",
      "Chimica",
      "Tecnologie e tecniche di rappresentazione grafica",
      "Tecnologie informatiche",
      "Scienze sportive e motorie",
      "Religione Cattolica",
    ],
    "2CT": [
      "Lingua e letteratura italiana",
      "Storia, cittadinanza e Costituzione",
      "Matematica",
      "Inglese",
      "Diritto ed economia",
      "Biologia",
      "Fisica",
      "Chimica",
      "Tecnologie e tecniche di rappresentazione grafica",
      "Scienze sportive e motorie",
      "Religione Cattolica",
      "Scienze e tecnologie applicate",
    ],
    "3CT": [
      "Lingua e letteratura italiana",
      "Storia, cittadinanza e Costituzione",
      "Matematica",
      "Inglese",
      "Scienze sportive e motorie",
      "Religione Cattolica",
      "Tecnologie e progettazione di sistemi elettrici ed elettronici",
      "Elettronica ed Elettrotecnica",
      "Sistemi automatici ",
    ],
    "4CT": [
      "Lingua e letteratura italiana",
      "Storia, cittadinanza e Costituzione",
      "Matematica",
      "Inglese",
      "Scienze sportive e motorie",
      "Religione Cattolica",
      "Tecnologie e progettazione di sistemi elettrici ed elettronici",
      "Elettronica ed Elettrotecnica",
      "Sistemi automatici ",
    ],
    "5CT": [
      "Lingua e letteratura italiana",
      "Storia, cittadinanza e Costituzione",
      "Matematica",
      "Inglese",
      "Scienze sportive e motorie",
      "Religione Cattolica",
      "Tecnologie e progettazione di sistemi elettrici ed elettronici",
      "Elettronica ed Elettrotecnica",
      "Sistemi automatici ",
    ],
  },
}